### ISSUE TITLE
Graph IRI enumaration does not work

### ISSUE THREAD

**Issue by arnikz** [candYgene/queries#6]
https://github.com/candYgene/queries/blob/master/countFeatures.rq

**Comment by c-martinez** [comment]
I am assuming that
```?feature_uri rdfs:label ?feature .```
should be
```?f rdfs:label ?feature .```

**Comment by c-martinez** [comment]
I'll replace the default graph:
```SPARQL
FROM ?_graph_iri 
WHERE {
...
}
```
For graph matching (if that is how this is called):
```SPARQL
WHERE {
  GRAPH ?_graph_iri {
...
  }
}
```
After a  quick test, results are the same -- but grlc can replace `?_graph_iri` on the graph matching case.
