### ISSUE TITLE
Can't use GROUP_CONCAT in the query

### ISSUE THREAD

**Issue by arnikz** [candYgene/queries#9]
See query: `getGeneAnnotations.rq`

`?go_id` -> `GROUP_CONCAT(?go_id, ', ') AS ?uniprot_goa`
...
`GROUP BY ...`

**Comment by c-martinez** [comment]
I think you want:

```(GROUP_CONCAT(?go_id; separator=", ") as ?uniprot_goa)```
...
```GROUP BY ?gene_id ?gene_name ?transcript_id ?sgn_des ?uniprot_acc ?uniprot_reviewed ?uniprot_existence ?uniprot_des```

Just committed a change which should make it work.

**Comment by arnikz** [comment]
@c-martinez the query works when executed against the SPARQL endpoint but doesn't show up in the API.

**Comment by c-martinez** [comment]
Ah! It seems it is a bug on grlc itself, not on the query... you are using the `clariah/grlc:dev` docker image?

**Comment by c-martinez** [comment]
Updated rdflib dependencies seems to fix the issue -- can you try again and reopen issue if necessary?
